apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
spec:
  clusterIP: None
  ports:
  - port: 26257
    targetPort: 26257
    name: grpc
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: cockroachdb

---

apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-node
spec:
  type: NodePort
  ports:
  - port: 26257
    targetPort: 26257
    nodePort: 30257
    name: grpc
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
  selector:
    app: cockroachdb